# Generated by Django 4.0.4 on 2022-06-08 17:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject_info',
        ),
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(to='main_app.student'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='main_app.subject', verbose_name='Przedmiot'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(validators=[main_app.models.validate_year], verbose_name='Wiek'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[^\\W\\d_]*$', 'Proszę podać litery')], verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], max_length=16, verbose_name='Płeć'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[^\\W\\d_]*$', 'Proszę podać litery')], verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Przedmiot'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[^\\W\\d_]*$', 'Proszę podać litery')], verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], max_length=16, verbose_name='Płeć'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[^\\W\\d_]*$', 'Proszę podać litery')], verbose_name='Nazwisko'),
        ),
        migrations.CreateModel(
            name='SchoolSubjectTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('subjects', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='Nazwa')),
                ('year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(2020), main_app.models.max_value_current_year], verbose_name='Rok')),
            ],
            options={
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PresenceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('present', models.BooleanField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(max_length=8, validators=[main_app.models.validate_grades], verbose_name='Ocena')),
                ('student', models.ManyToManyField(to='main_app.student', verbose_name='Uczeń')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subject', verbose_name='Przedmiot')),
                ('topic', models.ManyToManyField(to='main_app.schoolsubjecttopics', verbose_name='Temat')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.schoolclass', verbose_name='Rok rozpoczęcia nauki/klasa'),
        ),
    ]
