# Generated by Django 4.0.4 on 2022-06-08 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_teacher_subject_info_subject_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.schoolclass', verbose_name='Rok rozpoczęcia nauki/klasa'),
        ),
    ]
